name: deploy-toy-website-end-to-end
concurrency: toy-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # Build the application and database.
  build:
    uses: ./.github/workflows/build.yml

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  deploy-vnet:
      uses: ./.github/workflows/deploy-vnet.yml
      needs: [build, lint]
      with:
        environmentType: Test
        resourceGroupName: AzureSQLPrivateVNTest
        appName: cosmo
        createGateway: yes       
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  validate-infra-test:
      uses: ./.github/workflows/deploy-infra.yml 
      needs: [deploy-vnet]
      with:
        environmentType: Test
        resourceGroupName: AzureSQLPrivateVNTest
        appName: cosmo
        frontendSubnet: ${{ needs.deploy-vnet.outputs.frontendSubnet }}
        backendSubnet: ${{ needs.deploy-vnet.outputs.backendSubnet }}
        vnetId: ${{ needs.deploy-vnet.outputs.vnetId }}
        createWindowsServer1: true
        createLinuxServer1: true
        createWindowsDesktop: true
        adminDBLoginName: gary
        databaseName: slaesfloor
        vmSize: 'Standard_A0'  
        vmWindowsLoginUser: gary
        vmLinuxLoginUser: gary                  
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          adminDBPassword: ${{ secrets.ADMINDBPASSWORD }}
          vmWindowsLoginPassword: ${{ secrets.VMWINDOWSLOGINPASSWORD }}
          vmLinuxLoginPassword: ${{ secrets.VMLINUXLOGINPASSWORD }}